### ISSUE TITLE
Add an option to group sequence of the same action types

### ISSUE THREAD

**Issue by steida** [fcomb/redux-logger#127]
Some actions can be called hundreds times. It should be great to have an option to group them into one line.

**Comment by theaqua** [comment]
Probably you can use something like [log batched action receipt](https://github.com/fcomb/redux-logger#log-batched-actions).

**Comment by kyouko-taiga** [comment]
Does anyone actually implemented this?
Because the suggested solution doesn't seem so obvious to me.

I don't think we can use an `actionTransformer` to pull that off, as it does not have any influence whether or not the action will be displayed (`predicate` appears to be executed before). Overriding the logger doesn't solve the issue neither because we cannot know the type of the action being displayed until *after* the previous state is supposed to have been logged. The only option left is to play with the `predicate` option.

I managed to hide all subsequent actions like this:
```javascript
let lastActionType = null
const predicate = (getState, action) => {
  if (action.type != lastActionType) {
    lastActionType = action.type
    return true
  }
  return false
}
```

But this solution isn't optimal, as it only shows the first action of the batch, while it'd be great to know things such as how many times it was fired, as well as the state before its last occurence.

One solution could be to aggregate identical actions and then simulate an additional dispatch for that last one (as soon as another action type is fired, or after a timeout), but this looks a little too dirty to me.
