### ISSUE TITLE
Undefined error on headless browsers

### ISSUE THREAD

**Issue by bbenezech** [fcomb/redux-logger#46]
I have no idea if it is to be expected, but PhantomJS and Webkit crash with:
<img width="763" alt="screen shot 2015-10-10 at 16 42 55" src="https://cloud.githubusercontent.com/assets/26794/10411686/2571ab44-6f6e-11e5-9541-e7aaf5c3611f.png">

The pad function and the way it is called look pretty harmless and the error is Chinese to me :confetti_ball: 

Happened with Capybara->Poltergeist->PhantomJS 2.0.0

```javascript
  applyMiddleware(thunk, createLogger({
    predicate: (getState, action) => (process.env.NODE_ENV === 'development') // do not use with headless browsers
  }))
```
solved the issue for me of course.

**Comment by luisrudge** [comment]
have you tried jsdom?

**Comment by bbenezech** [comment]
No. But same thing with capybara-WebKit (QT)

**Comment by toxickg** [comment]
OK, it looks like PhantomJS 2.0 [doesn't support `repeat` function](http://kangax.github.io/compat-table/es6/#test-String.prototype_methods_String.prototype.repeat), because the version of WebKit used doesn't support it. According to this StackOverflow [answer](http://stackoverflow.com/a/27687648/352784) WebKit 538.1 used in PhantomJS 2.0 was released in November of 2013 (that's quite some time ago).

**Comment by toxickg** [comment]
@bbenezech You could try to use polyfill (e.g., [the one included in Babel](https://babeljs.io/docs/usage/polyfill/)) for this function and probably a few other functions as well.

**Comment by bbenezech** [comment]
Ok, thanks a lot, I ended up ditching babel-runtime and importing babel/polyfill instead.

For future ref.: http://stackoverflow.com/questions/31781756/is-there-any-practical-difference-between-using-babel-runtime-and-the-babel-poly
