### ISSUE TITLE
Support of TypeScript 

### ISSUE THREAD

**Issue by nizsheanez** [fcomb/redux-logger#86]
Is here any plan to add definitions to http://definitelytyped.org/ ?

**Comment by nizsheanez** [comment]
found https://github.com/DefinitelyTyped/DefinitelyTyped/pull/6003 
did some mistake

**Comment by dezoxel** [comment]
@evgenyrodionov what about native support of typings? I mean it would be great to have `*.d.ts` file in the repository itself, not in definitely typed repo. In this case clients don't need to install typings at all since typescript is smart enough in order to resolve typings based on `package.json`'s field: `"typings": "./index.d.ts"`

**Comment by evgenyrodionov** [comment]
@dezoxel hi! Yeah, let's do it, I'll merge your PR.

**Comment by corydeppen** [comment]
@dezoxel Did you make any progress towards creating a PR to include the definition file in this repo?
